### ISSUE TITLE
Drop intermediate calculated columns - add_income_source_cat function 

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#428]
**Based on Giovanni's feedback**

> 
>  2-	When I run the following code to test add_income_source_cat, 17 variables are added:
> 
> main<- dummy_raw_data$main %>%
>   select(c("uuid",starts_with("admin"),starts_with("cm"))) %>%
>   add_income_source_cat()
> 
> maybe it would be good to clarify that the output also includes not only the ranking of top 3 sources but also other accessory outputs (is this just because I am running it in local?)

**To reproduce** : 

```R 

library(humind)
library(dplyr)

df <- data.frame(
  uuid = 1:3,
  cm_income_source_assistance_n = c(50, 0, 0),
  cm_income_source_support_friends_n = c(0, 100, 0),
  cm_income_source_donation_n = c(30, 20, 1),
  cm_income_source_casual_n = c(50, 0, 0),
  cm_income_source_social_benefits_n = c(0, 30, 0),
  cm_income_source_rent_n = c(150, 0, 80),
  cm_income_source_remittances_n = c(25, 38, 0),
  cm_income_source_salaried_n = c(300, 60, 0),
  cm_income_source_own_business_n = c(0, 0, 50),
  cm_income_source_own_production_n = c(0, 0, 20),
  cm_income_source_other_n = c(0, 60, 0)
)

result <- add_income_source_cat(df)
```

**The issue:** In the previous example, the Original df is 12 variables, the resulted df is with 29 variables. It seems, only 3 variables with top in the name are expected to be added so the result df variables count should be 15, while the remaining intermediate 14 variables should be dropped from the output. 

**solution** 

Adding last step to keep only the ranking and the uuid in the result df, plus fixing a space in ```    unstable = c("cm_income_source_casual_n", "cm_income_source_social_benefits_n", "cm_income_source_rent_n", "cm_income_source_remittances_n"),``` & correction of category for ```  income_source_cat_rec <- function(df, var, emergency, unstable, stable, other){```
 
```R
#' Add income source categories, count, and top 3
#'
#' @param df A data frame.
#' @param emergency The names of the columns that contain emergency income sources.
#' @param unstable The names of the columns that contain unstable income sources.
#' @param stable The names of the columns that contain stable income sources.
#' @param other The name of the column that contains other income sources.
#' @param id_col The name of the column that contains the unique identifier.
#'
#' @export
add_income_source_cat <- function(
    df,
    emergency = c("cm_income_source_assistance_n", "cm_income_source_support_friends_n", "cm_income_source_donation_n"),
    unstable = c("cm_income_source_casual_n", "cm_income_source_social_benefits_n", "cm_income_source_rent_n", "cm_income_source_remittances_n"),
    stable = c("cm_income_source_salaried_n", "cm_income_source_own_business_n", "cm_income_source_own_production_n"),
    other = "cm_income_source_other_n",
    id_col = "uuid"){

  #------ Checks

  # Check that all are variables in the dataset
  if_not_in_stop(df, c(emergency, unstable, stable, other), "df")

  # Check that all are numeric
  are_cols_numeric(df, c(emergency, unstable, stable, other))

  #------ Compute the number of all income sources

  # Emergency
  df <- count_if_above_zero(df, emergency, "cm_income_source_emergency_n")

  # Unstable
  df <- count_if_above_zero(df, unstable, "cm_income_source_unstable_n")

  # Stable
  df <- count_if_above_zero(df, stable, "cm_income_source_stable_n")

  # Other
  df <- count_if_above_zero(df, other, "cm_income_source_other_n")

  # Ranking
  df <- rank_top3_vars(
    df = df,
    vars = c(emergency, unstable, stable, other),
    new_colname_top1 = "cm_income_source_top1",
    new_colname_top2 = "cm_income_source_top2",
    new_colname_top3 = "cm_income_source_top3",
    id_col = id_col)

  # Add final category:

  # Handy function - Recode income sources
  income_source_cat_rec <- function(df, var, emergency, unstable, stable, other){
    dplyr::mutate(
      df,
      "{var}" := dplyr::case_when(
        !!rlang::sym(var) %in% emergency ~ "emergency",
        !!rlang::sym(var) %in% unstable ~ "unstable",
        !!rlang::sym(var) %in% stable ~ "stable",
        !!rlang::sym(var) %in% other ~ "other",
        .default = NA_character_)
    )
  }

  # Recode income sources across cm_income_source_top* columns
  df <- income_source_cat_rec(df, "cm_income_source_top1", emergency, unstable, stable, other)
  df <- income_source_cat_rec(df, "cm_income_source_top2", emergency, unstable, stable, other)
  df <- income_source_cat_rec(df, "cm_income_source_top3", emergency, unstable, stable, other)

  # Keep only the necessary columns
  final_columns <- c(id_col, "cm_income_source_top1", "cm_income_source_top2", "cm_income_source_top3")
  df <- df %>% dplyr::select(all_of(final_columns))

  return(df)
}

```

**Comment by lanawwas** [comment]
@gnoblet if you agree with the proposed solution and changes I will correct it and push it in a commit to dev branch

**Comment by gnoblet** [comment]
If we go that way, we'd lose the rest of the dataframe, right?

Would suggest we remove the added binary columns in the backend function `count_if_above_zero()` [: here](https://github.com/impact-initiatives-hppu/humind/blob/main/R/count_if_above_zero.R ).

**Proposed change**:

```r
#' Count across if above zero
#'
#' @param df A data frame.
#' @param vars Vector of column names.
#' @param new_colname The name of the new column.
#'
#' @export
count_if_above_zero <- function(df, vars, new_colname){

  #----- Checks

  # Check if vars exists in df
  if_not_in_stop(df, vars, "df")

  # Check if vars are numeric
  are_cols_numeric(df, vars)

  # Paste "_d" to vars names and throw a warning that these will be replaced
  vars_d <- paste0(vars, "_d")
  vars_d_in_df <- intersect(vars_d, colnames(df))
  if (length(vars_d_in_df) > 0) {
    rlang::warn(glue::glue("The following variables exist in 'df' and will be removed: ", glue::glue_collapse(vars_d_in_df, sep = ", ", last = " and ")))
  }

  # Warn if new colname exist
  if (new_colname %in% colnames(df)) {
    rlang::warn(paste0(new_colname, " already exists in 'df'. It will be replaced."))
  }

  #----- Compute

  # Create dummy vars if above 0, 0 if 0, NA if below 0
  df <- dplyr::mutate(
    df,
    dplyr::across(
      .cols = dplyr::all_of(vars),
      .fns = \(x) dplyr::case_when(
        x > 0 ~ 1,
        x == 0 ~ 0,
        .default = NA_real_
      ),
      .names = "{.col}_d")
  )

  df <- sum_vars(
    df,
    vars_d,
    new_colname = new_colname,
    imputation = "none",
    na_rm = FALSE
  )

  df <- dplyr::select(df, -dplyr::all_of(vars_d)

    return(df)
  }
  ```
  
  Thoughts @lanawwas ?

**Comment by lanawwas** [comment]
> If we go that way, we'd lose the rest of the dataframe, right?
> 
> Would suggest we remove the added binary columns in the backend function `count_if_above_zero()` [: here](https://github.com/impact-initiatives-hppu/humind/blob/main/R/count_if_above_zero.R).
> 
> **Proposed change**:
> 
> ```r
> #' Count across if above zero
> #'
> #' @param df A data frame.
> #' @param vars Vector of column names.
> #' @param new_colname The name of the new column.
> #'
> #' @export
> count_if_above_zero <- function(df, vars, new_colname){
> 
>   #----- Checks
> 
>   # Check if vars exists in df
>   if_not_in_stop(df, vars, "df")
> 
>   # Check if vars are numeric
>   are_cols_numeric(df, vars)
> 
>   # Paste "_d" to vars names and throw a warning that these will be replaced
>   vars_d <- paste0(vars, "_d")
>   vars_d_in_df <- intersect(vars_d, colnames(df))
>   if (length(vars_d_in_df) > 0) {
>     rlang::warn(glue::glue("The following variables exist in 'df' and will be removed: ", glue::glue_collapse(vars_d_in_df, sep = ", ", last = " and ")))
>   }
> 
>   # Warn if new colname exist
>   if (new_colname %in% colnames(df)) {
>     rlang::warn(paste0(new_colname, " already exists in 'df'. It will be replaced."))
>   }
> 
>   #----- Compute
> 
>   # Create dummy vars if above 0, 0 if 0, NA if below 0
>   df <- dplyr::mutate(
>     df,
>     dplyr::across(
>       .cols = dplyr::all_of(vars),
>       .fns = \(x) dplyr::case_when(
>         x > 0 ~ 1,
>         x == 0 ~ 0,
>         .default = NA_real_
>       ),
>       .names = "{.col}_d")
>   )
> 
>   df <- sum_vars(
>     df,
>     vars_d,
>     new_colname = new_colname,
>     imputation = "none",
>     na_rm = FALSE
>   )
> 
>   df <- dplyr::select(df, -dplyr::all_of(vars_d)
> 
>     return(df)
>   }
> ```
> 
> Thoughts @lanawwas ?

Your solution would be cleaner!
