### ISSUE TITLE
Rename function add_income_source_cat.R

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#429]
Based on Giovanni's feedback: 

> 1-	Maybe the name of the function is misleading (suggest changing it to add_income_source_cat_rank)

**Proposed new name** : add_income_source_cat_rank.R

Linked issues: #428

**Comment by lanawwas** [comment]
Yet another renaming job @gnoblet do we keep it as proposed? Or do we use add_income_source_rank.R ?

**Comment by gnoblet** [comment]
add_income_source_rank.R works for me!
