### ISSUE TITLE
add_income_source_cat.R - Warning message: cm_income_source_other_n already exists in 'df'. It will be replaced.

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#431]
>

>  4-	The following warning shows when using the “main” from the dummy data. I hope it is not rewriting new modified data on top of an existing column.
> 
> Warning message:
> cm_income_source_other_n already exists in 'df'. It will be replaced.

We need to check the function calculation steps. And if it is expected to be replaced

**Comment by gnoblet** [comment]
I think it is! (?) Maybe if a change of naming is needed, all the output columns can be named different
