### ISSUE TITLE
[Failure] 30 3 | add_handwashing_facility_cat function works with default parameters for remote surveys

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#440]
## The issue

- The `df_remote` data frame is not being filtered correctly. The code is using the original `df` instead of the filtered `df_remote` in the mutation step.

- The function is not handling the case where `wash_handwashing_facility` is `available` for remote surveys.

## Proposed Solution 

To fix these issues, modify your add_handwashing_facility_cat function as follows:

```r
add_handwashing_facility_cat <- function(
  df,
  # ... (keep other parameters the same)
){
  # Option 1: Process for In-person modality (keep this part the same)

  # Option 2: Process for Remote modality or No permission to see
  df_remote <- dplyr::filter(df, !!rlang::sym(survey_modality) %in% survey_modality_remote | !!rlang::sym(facility) %in% facility_options2)
  df_remote <- dplyr::mutate(
    df_remote,  # Change this from df to df_remote
    wash_handwashing_facility_yn = dplyr::case_when(
      !!rlang::sym(facility) == "available" ~ 1,  # Add this line to handle "available" for remote surveys
      !!rlang::sym(reported_facility) %in% facility_reported_options[1:3] ~ 1,
      !!rlang::sym(reported_facility) %in% facility_reported_options[4:5] ~ 0,
      .default = NA_real_
    ),
    wash_soap_yn = dplyr::case_when(
      !!rlang::sym(observed_soap) == observed_soap_options[1] ~ 1,
      !!rlang::sym(observed_soap) %in% observed_soap_options[-1] ~ 0,
      .default = NA_real_
    ),
    wash_handwashing_facility_jmp_cat = dplyr::case_when(
      wash_handwashing_facility_yn == 1 & wash_soap_yn == 1 ~ "basic",
      wash_handwashing_facility_yn == 1 & wash_soap_yn == 0 ~ "limited",
      wash_handwashing_facility_yn == 0 ~ "no_facility",
      .default = NA_character_
    ))

  # Combine both processed data frames
  df <- dplyr::bind_rows(df_in_person, df_remote)

  return(df)
}
```

## The error
── Failure ('test-add_handwashing_facility_cat.R:30:3'): add_handwashing_facility_cat function works with default parameters for remote surveys ──
result$wash_handwashing_facility_yn[4] not equal to 1.
1/1 mismatches
[1] NA - 1 == NA

── Failure ('test-add_handwashing_facility_cat.R:31:3'): add_handwashing_facility_cat function works with default parameters for remote surveys ──
result$wash_handwashing_facility_yn[6] not equal to 0.
1/1 mismatches
[1] 1 - 0 == 1

── Failure ('test-add_handwashing_facility_cat.R:32:3'): add_handwashing_facility_cat function works with default parameters for remote surveys ──
result$wash_soap_yn[4] not equal to 0.
1/1 mismatches
[1] 1 - 0 == 1

── Failure ('test-add_handwashing_facility_cat.R:33:3'): add_handwashing_facility_cat function works with default parameters for remote surveys ──
result$wash_handwashing_facility_jmp_cat[4] not equal to "limited".
1/1 mismatches
x[1]: NA
y[1]: "limited"

── Failure ('test-add_handwashing_facility_cat.R:34:3'): add_handwashing_facility_cat function works with default parameters for remote surveys ──
result$wash_handwashing_facility_jmp_cat[6] not equal to "no_facility".
1/1 mismatches
x[1]: NA
y[1]: "no_facility"

**Comment by gnoblet** [comment]
@lanawwas closing as won't fix as it relates to an hold version of add_handwashing_facility_cat.R.
