### ISSUE TITLE
[Failure] 47 3 | add_handwashing_facility_cat function categorizes handwashing facility status correctly

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#441]
## The error

── Failure ('test-add_handwashing_facility_cat.R:47:3'): add_handwashing_facility_cat function categorizes handwashing facility status correctly ──
result$wash_handwashing_facility_jmp_cat[5] not equal to "basic".
1/1 mismatches
x[1]: NA
y[1]: "basic"

## The Issue: 

Based on the error message, it appears that the `add_handwashing_facility_cat` function is not correctly categorizing the handwashing facility status for the 5th row of the test data. The test expects the result to be "basic", but it's returning NA. 

From the JMP 
  

> Handwashing ladder
> 
>     Basic
> 
>     Availability of a handwashing facility with soap and water at home
> 
>     Limited
> 
>     Availability of a handwashing facility lacking soap and/or water at home
> 
>     No facility
> 
>     No handwashing facility on premises

The dummy data row 5:

```r
    survey_modality = "in_person"
    wash_handwashing_facility = "available"
    wash_handwashing_facility_observed_soap = "soap_available"
    wash_handwashing_facility_observed_water = "water_available"
```

- For in-person surveys, the function should categorize the handwashing facility as "basic" when:
   - The facility is available
   - Soap is available
   - Water is available

This should be categorized as "basic".

## Proposed Solution 

```r
  # Option 1: Process for In-person modality
  df_in_person <- dplyr::filter(df, !!rlang::sym(survey_modality) %in% survey_modality_in_person)
  df_in_person <- dplyr::mutate(
    df_in_person,
    wash_handwashing_facility_yn = dplyr::case_when(
      !!rlang::sym(facility) == facility_options1[1] ~ 1,
      !!rlang::sym(facility) == facility_options1[2] ~ 0,
      .default = NA_real_
    ),
    wash_soap_yn = dplyr::case_when(
      !!rlang::sym(observed_soap) == observed_soap_options[1] ~ 1,
      !!rlang::sym(observed_soap) %in% observed_soap_options[-1] ~ 0,
      .default = NA_real_
    ),
    wash_handwashing_facility_jmp_cat = dplyr::case_when(
      wash_handwashing_facility_yn == 1 & wash_soap_yn == 1 & !!rlang::sym(observed_water) == observed_water_options[1] ~ "basic",
      wash_handwashing_facility_yn == 1 & (wash_soap_yn == 0 | !!rlang::sym(observed_water) == observed_water_options[2]) ~ "limited",
      wash_handwashing_facility_yn == 0 ~ "no_facility",
      .default = NA_character_
    ))
```

**Comment by gnoblet** [comment]
@lanawwas I'm currently reviewing this function (including param names and access). Will look at the issues created and push commits inclusive of your proposals!

**Comment by gnoblet** [comment]
The error seems to come intially from the sectoral guidance. Then it's been added to the MSNI guidance from there. Will propose a first fix along these lines above. But we will have to coordinate with PHU, especially when it comes to remote options or no permission to see.

**Comment by gnoblet** [comment]
Latest commit related to this issue 3bc0577ec9206011f8c47ef9f734a6ba8d2ec584.

**Comment by lanawwas** [comment]
Handled in Ticket #450
