### ISSUE TITLE
Check `add_handwashing_facility_cat()`

### ISSUE THREAD

**Issue by gnoblet** [impact-initiatives-hppu/humind#450]
See commit 01ecbc0c968440022c3fe9b509e36eccd6a2ff35

Would be great to:

- [x] check that the logic is correct
- [x] write the testing structure

Point open to discussion: at this stage, we don't need to have all the parameters as they won't be used to differentiate for remote and no permission to see cases. Should we remove?

**Comment by gnoblet** [comment]
Last commit related to this function 3bc0577ec9206011f8c47ef9f734a6ba8d2ec584

**Comment by lanawwas** [comment]
Done, pending approval and review for  https://github.com/impact-initiatives-hppu/humind/pull/452, so the changes will be integrated and merged to dev branch

**Comment by gnoblet** [comment]
Closed with #452
