### ISSUE TITLE
Update DESCRIPTION to include all roles and Authors

### ISSUE THREAD

**Issue by lanawwas** [impact-initiatives-hppu/humind#482]

**Comment by gnoblet** [comment]
Started to update here: c1e335c9578d135ef637bc823b5348a7afbdf875
Feel free to assign whatever you'd like. Let's also add @BacotRaphael !

**Comment by gnoblet** [comment]
See commit 0b6e14ef1331900e9f469d353a84ceda7c8feff1 for a minor change

**Comment by lanawwas** [comment]
Versions: 

v2024.1.0 : MSNA 2024
v2024.1.1 : patch fix for the MSNA 2024
v2024.2.0 : adding major functions and features. 

v2025.1.0 : MSNA 2025
.
.
so on

**Comment by gnoblet** [comment]
See 12aa60d506428b690097ee318d8c7016288910e5
