### ISSUE TITLE
`add_age_cat()` breaks should behave with a +1 increment

### ISSUE THREAD

**Issue by gnoblet** [impact-initiatives-hppu/humind#504]
Issue: 
To be able to have the following thresholds: 0-17, 18-59, 120+, the current breaks must be written not intuitively as follows:
```r
 add_age_cat("resp_age", breaks = c(-1, 17, 59, 120))
```

Proposed change:
```r
add_age_cat("resp_age", breaks = c(0, 18, 60, 121))
```

**Comment by gnoblet** [comment]
@lanawwas assigning it to you since you worked on it. Feel free to disagree and close the issue.

**Comment by lanawwas** [comment]
We move this to the next release, v2024.1.2

**Comment by gnoblet** [comment]
Need fixing of `num_cat()`
