### ISSUE TITLE
add_loop_edu_disrupted_d, must change an argument 

### ISSUE THREAD

**Issue by martivit** [impact-initiatives-hppu/humind#520]
In:
   
   add_loop_edu_disrupted_d()
    
   the argument  --> occupation = "edu_disrupted_occupation"
    
   is not mandatory. As it is now, if not present in the data, it stops and the function can not be called

**Comment by gnoblet** [comment]
We could add an option to have it NULL for occupation since it is a tier 1 indicator that must be asked if relevant and not too sensitive.
