### ISSUE TITLE
Correction of comp_edu_score_attendance function

### ISSUE THREAD

**Issue by Muteba123** [impact-initiatives-hppu/humind#532]
According to the MSNI analytical framework, in the education sector, the variable comp_edu_score_attendance takes the value 4 when edu_no_access_n is greater than 0 and edu_barrier_protection_n is greater than 0. Looking at the code used in the GitHub to calculate the variable comp_edu_score_attendance, I notice that it takes the value 4 when edu_no_access_n is greater than 0 or edu_barrier_protection_n is greater than 0. So there is a disjunction instead of a conjunction. Which contradicts the analytical framework.

  # Compute score for attendance and barriers
  df <- dplyr::mutate(
    df,
    comp_edu_score_attendance = dplyr::case_when(
      # No school-aged child
      !!rlang::sym(schooling_age_n) == 0 ~ 1,
      # Non-attendance and protection barriers
      !!rlang::sym(no_access_n) >= 1 | !!rlang::sym(barrier_protection_n) >= 1 ~ 4,  ### (Here is the problem observed)
      # Non attendance only
      !!rlang::sym(no_access_n) >= 1 ~ 3,
      # All attending
      !!rlang::sym(no_access_n) == 0 ~ 1,
      .default = NA_real_
    )
  )

**Comment by gnoblet** [comment]
Agreed. Correction should be:

```r
df <- dplyr::mutate(
  df,
  comp_edu_score_attendance = dplyr::case_when(
  # No school-aged child
  !!rlang::sym(schooling_age_n) == 0 ~ 1,
  # Non-attendance and protection barriers
  !!rlang::sym(no_access_n) >= 1 & !!rlang::sym(barrier_protection_n) >= 1 ~ 4, ### (Here is the problem observed)
  # Non attendance only
  !!rlang::sym(no_access_n) >= 1 ~ 3,
  # All attending
  !!rlang::sym(no_access_n) == 0 ~ 1,
  .default = NA_real_))
```
