### ISSUE TITLE
add_comp_snfi issue

### ISSUE THREAD

**Issue by ghost** [impact-initiatives-hppu/humind#545]
Hi,
Using the latest version of humind, we get an issue when we excute **humind::add_comp_snfi()** as : 

`Error in `are_values_in_set()`:
! All columns must be in the following set: 7_to_8, 4_to_6, 1_to_3, none, undefined
ℹ The following columns have values out of the set Please check.
snfi_shelter_issue_cat
✖ The values out of the set are:
snfi_shelter_issue_cat: other`

This error appears when we use the updated function add_shelter_issue_cat by recoding : 
```
undefined = c("dnk", "pnta"), 
other=c("other")
```

**Comment by gnoblet** [comment]
Additional note: the documentation for param "issue_cat_levels" still has "none" as the first option.

**Comment by sunheemoraes** [comment]
> Additional note: the documentation for param "issue_cat_levels" still has "none" as the first option.

Thank you for the catch @gnoblet . Change commited.

**Comment by sunheemoraes** [comment]
Linking to https://github.com/impact-initiatives-hppu/humind/issues/548 since we will recode functions using separate parameters; no longer need for "_levels"
